webtalk_init -webtalk_dir /home/yarib/ZYBO_projects/app_workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 29 07:35:09 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nefo7bl7rh9lngksqlcr9o6evj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1503852157000" -context "sdk\\\\application/1503852157000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503852157000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503852157000"
webtalk_add_data -client sdk -key uid -value "1503852287000" -context "sdk\\\\application/1503852287000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503852287000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503852287000"
webtalk_add_data -client sdk -key uid -value "1503853310000" -context "sdk\\\\application/1503853310000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503853310000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503853310000"
webtalk_add_data -client sdk -key uid -value "1503853344000" -context "sdk\\\\application/1503853344000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503853344000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503853344000"
webtalk_add_data -client sdk -key uid -value "1503854875000" -context "sdk\\\\application/1503854875000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503854875000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503854875000"
webtalk_add_data -client sdk -key uid -value "1503958021000" -context "sdk\\\\application/1503958021000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1503958021000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1503958021000"
webtalk_transmit -clientid 3850261428 -regid "" -xml /home/yarib/ZYBO_projects/app_workspace/webtalk/usage_statistics_ext_sdk.xml -html /home/yarib/ZYBO_projects/app_workspace/webtalk/usage_statistics_ext_sdk.html -wdm /home/yarib/ZYBO_projects/app_workspace/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
